print('Informe o nome do primeiro gato:')
nomeGato1 = input()
print('Informe o nome do segundo gato:')
nomeGato2 = input()
print('Informe o nome do terceiro gato:')
nomeGato3 = input()
print('Informe o nome do quarto gato:')
nomeGato4 = input()
print('Informe o nome do quinto gato:')
nomeGato5 = input()
print('Informe o nome do sexto gato:')
nomeGato6 = input()
print('Os nomes dos gatos sao:')
print(nomeGato1 + ' ' + nomeGato2 + ' ' + nomeGato3 + ' ' + nomeGato4 + ' ' + nomeGato5 + ' ' + nomeGato6)
